version: "3"
# 有几个服务组成 docker compose
services:
  mysql8:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      # 初始化脚本【在本目录下的script文件夹下】
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      # 外部访问用 13316
      - 13316:3306
  redis:
    image: "bitnami/redis:latest"
    restart: always
    environment:
      # 无需密码就能连接redis
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017